In [4]:
import pandas as pd
import plotly.express as px

In [ ]:
dados_entrada = "data_expanded_3.csv"

df = pd.read_csv(f'{dados_entrada}', sep=',', encoding='utf-8')

In [6]:
df.head()

,n_empenho,unidade_gestora,credor,valor_empenhado,valor_liquidado,valor_total,funcao,programa,acao,subacao,...,n_licitacao,obs_empenho,tipo_despesa,despesa,fonte_recurso,cat_economica,grupo_despesa,modalidade_aplicacao,elemento_despesa,data
0,2025NE000016,ESCOLA POLITÉCNICA DE PERNAMBUCO,TOGGI SERVICE LIMPEZA E CONSERVACAO LTDA,0.0,0.0,5534.49,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,0035.2023.CPL.POLI.PE.0002.POLI,"REFERENTE A CONTRATAÇÃO DE LIMPEZA ESCOLAR, CO...",NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,LOCAÇÃO DE MÃO-DE-OBRA,2025-01-02
1,2025NE000017,ESCOLA POLITÉCNICA DE PERNAMBUCO,RM TERCEIRIZACAO E GESTAO DE RECURSOS HUMANOS ...,0.0,0.0,429.95,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,0011.2021.CCPLE-IV.PE.0011.SAD.CONSUMO.POLI,REFERENTE A SOLICITAÇÃO PARA SERVIÇO DE APOIO ...,NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,OUTROS SERVIÇOS DE TERCEIROS,2025-01-02
2,2025NE000024,ESCOLA POLITÉCNICA DE PERNAMBUCO,MUNICIPIO DO RECIFE,0.0,0.0,124.04,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,NaN,REFERENTE A SOLICITAÇÃO PARA MULTAS E JUROS DO...,NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,OBRIGAÇÕES TRIBUTÁRIAS E CONTRIBUTIVAS,2025-02-13
3,2025NE000453,ESCOLA POLITÉCNICA DE PERNAMBUCO,RM TERCEIRIZACAO E GESTAO DE RECURSOS HUMANOS ...,0.0,0.0,1132.84,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,0609.2024.AC-78.PE.0278.SAD,REF. A CONTRATAÇÃO DE SERVIÇO DE RECEPÇÃO. SE...,NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,OUTROS SERVIÇOS DE TERCEIROS,2025-08-20
4,2025NE000489,ESCOLA POLITÉCNICA DE PERNAMBUCO,BBC SERVICOS DE VIGILANCIA LTDA EM RECUPERACAO...,0.0,0.0,4877.96,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,0190.2022.PREG-IX.PE.0126.SAD,REF. AS DESPESAS COM O REAJUSTE E PRORROGAÇÃO ...,NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,OUTROS SERVIÇOS DE TERCEIROS,2025-08-28

#### Limpando o Dataset

Excluindo colunas sem utilização

In [ ]:
# df = df.drop(columns=['mes_num', 'ano', 'mes', 'dia', 'trimestre', 'subfuncao', 'arquivo_origem'])

In [ ]:
# df.to_csv('data_original.csv', index=False)

#### Explorando o Dataset

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12359 entries, 0 to 12358
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   n_empenho             12359 non-null  object
 1   unidade_gestora       12359 non-null  object
 2   credor                12359 non-null  object
 3   valor_empenhado       12359 non-null  float64
 4   valor_liquidado       12359 non-null  float64
 5   valor_total           12359 non-null  float64
 6   funcao                12359 non-null  object
 7   programa              12359 non-null  object
 8   acao                  12359 non-null  object
 9   subacao               12359 non-null  object
 10  modalidade_empenho    12359 non-null  object
 11  modalidade_licitacao  10001 non-null  object
 12  n_licitacao           9019 non-null   object
 13  obs_empenho           12246 non-null  object
 14  tipo_despesa          12356 non-null  object
 15  despesa               12356 non-null  object
 16  fonte_recurso         12356 non-null  object
 17  cat_economica         12356 non-null  object
 18  grupo_despesa         12356 non-null  object
 19  modalidade_aplicacao  12356 non-null  object
 20  elemento_despesa      12356 non-null  object
 21  data                  12359 non-null  object
dtypes: float64(3), object(19)
memory usage: 2.1+ MB

In [6]:
df.head()

,n_empenho,unidade_gestora,credor,valor_empenhado,valor_liquidado,valor_total,funcao,programa,acao,subacao,...,n_licitacao,obs_empenho,tipo_despesa,despesa,fonte_recurso,cat_economica,grupo_despesa,modalidade_aplicacao,elemento_despesa,data
0,2025NE000016,ESCOLA POLITÉCNICA DE PERNAMBUCO,TOGGI SERVICE LIMPEZA E CONSERVACAO LTDA,0.0,0.0,5534.49,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,0035.2023.CPL.POLI.PE.0002.POLI,"REFERENTE A CONTRATAÇÃO DE LIMPEZA ESCOLAR, CO...",NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,LOCAÇÃO DE MÃO-DE-OBRA,2025-01-02
1,2025NE000017,ESCOLA POLITÉCNICA DE PERNAMBUCO,RM TERCEIRIZACAO E GESTAO DE RECURSOS HUMANOS ...,0.0,0.0,429.95,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,0011.2021.CCPLE-IV.PE.0011.SAD.CONSUMO.POLI,REFERENTE A SOLICITAÇÃO PARA SERVIÇO DE APOIO ...,NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,OUTROS SERVIÇOS DE TERCEIROS,2025-01-02
2,2025NE000024,ESCOLA POLITÉCNICA DE PERNAMBUCO,MUNICIPIO DO RECIFE,0.0,0.0,124.04,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,NaN,REFERENTE A SOLICITAÇÃO PARA MULTAS E JUROS DO...,NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,OBRIGAÇÕES TRIBUTÁRIAS E CONTRIBUTIVAS,2025-02-13
3,2025NE000453,ESCOLA POLITÉCNICA DE PERNAMBUCO,RM TERCEIRIZACAO E GESTAO DE RECURSOS HUMANOS ...,0.0,0.0,1132.84,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,0609.2024.AC-78.PE.0278.SAD,REF. A CONTRATAÇÃO DE SERVIÇO DE RECEPÇÃO. SE...,NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,OUTROS SERVIÇOS DE TERCEIROS,2025-08-20
4,2025NE000489,ESCOLA POLITÉCNICA DE PERNAMBUCO,BBC SERVICOS DE VIGILANCIA LTDA EM RECUPERACAO...,0.0,0.0,4877.96,EDUCAÇÃO,APOIO GERENCIAL E TECNOLÓGICO PARA O CONHECIME...,GESTÃO DAS ATIVIDADES DA REITORIA E UNIDADES D...,GESTÃO ADMINISTRATIVA DAS UNIDADES DE ENSINO D...,...,0190.2022.PREG-IX.PE.0126.SAD,REF. AS DESPESAS COM O REAJUSTE E PRORROGAÇÃO ...,NORMAL,CUSTEIO,RECURSOS NÃO VINCULADOS DE IMPOSTOS,DESPESAS CORRENTES,OUTRAS DESPESAS CORRENTES,APLICAÇÕES DIRETA,OUTROS SERVIÇOS DE TERCEIROS,2025-08-28

In [60]:
df.groupby("grupo_despesa").agg(
        valor_total=("valor_total", "sum"),
        qtd_empenhos=("n_empenho", "count")
    )

                             valor_total  qtd_empenhos
grupo_despesa
AMORTIZAÇÃO DA DÍVIDA       9.548514e+04             3
INVESTIMENTOS               3.294116e+07           222
JUROS E ENCARGOS DA DÍVIDA  6.823144e+04             3
OUTRAS DESPESAS CORRENTES   2.541200e+08          7532
PESSOAL E ENCARGOS SOCIAIS  1.328765e+09           122

In [7]:
df = df.drop_duplicates()

In [40]:
df = df[(df['valor_total'].sort_values() > 0) & (df['valor_empenhado'].sort_values() > 0) & (df['valor_liquidado'].sort_values() > 0)]

In [26]:
df['data'] = pd.to_datetime(df['data'], errors="coerce")

df['ano'] = df['data'].dt.year

C:\Users\Adel\AppData\Local\Temp\ipykernel_18768\2616728326.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['data'] = pd.to_datetime(df['data'], errors="coerce")
C:\Users\Adel\AppData\Local\Temp\ipykernel_18768\2616728326.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ano'] = df['data'].dt.year

In [41]:
df['ano'].value_counts()

# indicador de risco: valor empenhado / valor liquidado
# serie temporal por unidade gestora e global + previsão de demanda futura (nome: risco de empenho, liquidação e pagamento)

ano
2023    4241
2025    2755
2024     787
2026     100
Name: count, dtype: int64

In [42]:
df['unidade_gestora'].unique()

# kpis por unidade gestora e global
# adiconar um filtro drilldown 
# filtro por faixa de valor empenhado, liquidado e total

array(['ESCOLA POLITÉCNICA DE PERNAMBUCO',
       'HOSPITAL UNIVERSITÁRIO OSWALDO CRUZ',
       'FUNDAÇÃO UNIVERSIDADE DE PERNAMBUCO - PRO-REITORIA ADMINISTRATIVA'],
      dtype=object)

In [43]:
df['valor_empenhado'].describe()

count    7.883000e+03
mean     2.087864e+05
std      4.423837e+06
min      1.540000e+00
25%      1.614285e+03
50%      3.600000e+03
75%      1.431473e+04
max      2.206730e+08
Name: valor_empenhado, dtype: float64

In [51]:
fig = px.histogram(df[df['valor_empenhado'].sort_values() < 50000], x='valor_empenhado', nbins=10, title='Distribuição do Valor Empenhado')
fig.show()

C:\Users\Adel\AppData\Local\Temp\ipykernel_18768\1058975235.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.histogram(df[df['valor_empenhado'].sort_values() < 50000], x='valor_empenhado', nbins=10, title='Distribuição do Valor Empenhado')

In [13]:
df['valor_liquidado'].describe()

count    1.235900e+04
mean     1.345956e+05
std      3.534547e+06
min      0.000000e+00
25%      0.000000e+00
50%      2.000000e+03
75%      7.800000e+03
max      2.206730e+08
Name: valor_liquidado, dtype: float64

In [14]:
fig = px.histogram(df, x='valor_liquidado', nbins=50, title='Histograma do Valor Liquidado')
fig.show()

In [15]:
df['valor_total'].describe()

count    1.235900e+04
mean     1.356458e+05
std      3.517768e+06
min      0.000000e+00
25%      0.000000e+00
50%      2.000000e+03
75%      9.086455e+03
max      2.206730e+08
Name: valor_total, dtype: float64

In [ ]:
df_coluna_valor = df[(df['valor_total'] <= 40000) & (df['valor_total'] > 5000)]

# criar visualizações por faixas: até 5000, de 5000 a 40000 e acima de 40k

In [17]:
# fig = px.box(df_coluna_valor, y='valor_total', title='Violino do Valor Total')
# fig.show()

In [18]:
fig = px.violin(df_coluna_valor, y='valor_total', title='Violino do Valor Total', box=True)
fig.show()

In [19]:
fig = px.histogram(df, x='valor_total', nbins=10, title='Histograma do Valor Total')
fig.show()

In [52]:
fig = px.scatter(df, x='valor_empenhado', y='valor_total', title='Dispersão entre Valor Empenhado e Valor Liquidado', color='ano')

fig.show()

# criar aba de eventos futuros ou nos indicadores

In [58]:
print(f'{df.shape[0]}')

7883